"$schema" = "https://starship.rs/config-schema.json"

# ディレクトリ + Git ブランチ + Git ステータス + コマンド実行時間のみ表示
format = """
$directory\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
$character"""

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"

[directory]
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = "[$branch]($style) "

[git_status]
format = '([$all_status$ahead_behind]($style) )'

[cmd_duration]
min_time = 2000
format = "[$duration]($style) "
