[tools]
# Infrastructure
terraform = "latest"
awscli = { version = "latest", symlink_bins = "true" }

# Kubernetes
kubectl = "latest"
helm = "latest"

# Runtimes
node = "latest"
bun = "latest"
python = "latest"
ruby = "latest"
